export enum ErrorCodeEnum {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    BAD_LENGTH_PASSWORD = 'BAD_LENGTH_PASSWORD',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    VALIDATION = 'VALIDATION',
    TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
    UNKNOWN = 'UNKNOWN'
}
